arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localization.dart
preferred-supported-locales:
  - en
  - be
  - uk
  - pl
  - pt
  - fr
  - de
  - zh
  - hi
