name: flutter_currency_picker
description: |
  Currency Picker -- simple representation layer (double to formatted number), 
  wrapper on top of SearchAnchor
version: 1.1.7
homepage: https://github.com/lyskouski/flutter_currency_picker
repository: https://github.com/lyskouski/flutter_currency_picker
issue_tracker: https://github.com/lyskouski/flutter_currency_picker/issues

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  generate: true
