// Copyright 2023 The terCAD team. All rights reserved.
// Use of this source code is governed by a MIT license
// that can be found in the LICENSE file.

import 'package:flutter_currency_picker/src/currency.dart';
import 'package:flutter_currency_picker/src/currency_defaults.dart';

// Order by Most traded currencies:
// https://en.wikipedia.org/wiki/Template:Most_traded_currencies
List<Currency> currencyList = [
  (
    code: 'USD',
    name: CurrencyDefaults.labels.currencyUSD,
    symbol: '\$',
    flag: 'USD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'EUR',
    name: CurrencyDefaults.labels.currencyEUR,
    symbol: '€',
    flag: 'EUR',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'JPY',
    name: CurrencyDefaults.labels.currencyJPY,
    symbol: '¥',
    flag: 'JPY',
    decimalDigits: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'GBP',
    name: CurrencyDefaults.labels.currencyGBP,
    symbol: '£',
    flag: 'GBP',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'AUD',
    name: CurrencyDefaults.labels.currencyAUD,
    symbol: '\$',
    flag: 'AUD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'CAD',
    name: CurrencyDefaults.labels.currencyCAD,
    symbol: '\$',
    flag: 'CAD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'CHF',
    name: CurrencyDefaults.labels.currencyCHF,
    symbol: 'CHF',
    flag: 'CHF',
    decimalDigits: 2,
    thousandsSeparator: "'",
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'CNY',
    name: CurrencyDefaults.labels.currencyCNY,
    symbol: '¥',
    flag: 'CNY',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'HKD',
    name: CurrencyDefaults.labels.currencyHKD,
    symbol: '\$',
    flag: 'HKD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'NZD',
    name: CurrencyDefaults.labels.currencyNZD,
    symbol: '\$',
    flag: 'NZD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'SEK',
    name: CurrencyDefaults.labels.currencySEK,
    symbol: 'kr',
    flag: 'SEK',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'KRW',
    name: CurrencyDefaults.labels.currencyKRW,
    symbol: '₩',
    flag: 'KRW',
    decimalDigits: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'SGD',
    name: CurrencyDefaults.labels.currencySGD,
    symbol: '\$',
    flag: 'SGD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'NOK',
    name: CurrencyDefaults.labels.currencyNOK,
    symbol: 'kr',
    flag: 'NOK',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'MXN',
    name: CurrencyDefaults.labels.currencyMXN,
    symbol: '\$',
    flag: 'MXN',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'INR',
    name: CurrencyDefaults.labels.currencyINR,
    symbol: '₹',
    flag: 'INR',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'RUB',
    name: CurrencyDefaults.labels.currencyRUB,
    symbol: '₽',
    flag: 'RUB',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'ZAR',
    name: CurrencyDefaults.labels.currencyZAR,
    symbol: 'R',
    flag: 'ZAR',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'TRY',
    name: CurrencyDefaults.labels.currencyTRY,
    symbol: '₺',
    flag: 'TRY',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'BRL',
    name: CurrencyDefaults.labels.currencyBRL,
    symbol: 'R\$',
    flag: 'BRL',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'TWD',
    name: CurrencyDefaults.labels.currencyTWD,
    symbol: 'NT\$',
    flag: 'TWD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'DKK',
    name: CurrencyDefaults.labels.currencyDKK,
    symbol: 'kr',
    flag: 'DKK',
    decimalDigits: 2,
    thousandsSeparator: '',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'PLN',
    name: CurrencyDefaults.labels.currencyPLN,
    symbol: 'zł',
    flag: 'PLN',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'THB',
    name: CurrencyDefaults.labels.currencyTHB,
    symbol: '฿',
    flag: 'THB',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'IDR',
    name: CurrencyDefaults.labels.currencyIDR,
    symbol: 'Rp',
    flag: 'IDR',
    decimalDigits: 0,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'HUF',
    name: CurrencyDefaults.labels.currencyHUF,
    symbol: 'Ft',
    flag: 'HUF',
    decimalDigits: 0,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'CZK',
    name: CurrencyDefaults.labels.currencyCZK,
    symbol: 'Kč',
    flag: 'CZK',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'ILS',
    name: CurrencyDefaults.labels.currencyILS,
    symbol: '₪',
    flag: 'ILS',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'CLP',
    name: CurrencyDefaults.labels.currencyCLP,
    symbol: '\$',
    flag: 'CLP',
    decimalDigits: 0,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'PHP',
    name: CurrencyDefaults.labels.currencyPHP,
    symbol: '₱',
    flag: 'PHP',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'AED',
    name: CurrencyDefaults.labels.currencyAED,
    symbol: 'د.إ',
    flag: 'AED',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'COP',
    name: CurrencyDefaults.labels.currencyCOP,
    symbol: '\$',
    flag: 'COP',
    decimalDigits: 0,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'SAR',
    name: CurrencyDefaults.labels.currencySAR,
    symbol: '﷼',
    flag: 'SAR',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'MYR',
    name: CurrencyDefaults.labels.currencyMYR,
    symbol: 'RM',
    flag: 'MYR',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'RON',
    name: CurrencyDefaults.labels.currencyRON,
    symbol: 'L',
    flag: 'RON',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'AFN',
    name: CurrencyDefaults.labels.currencyAFN,
    symbol: '؋',
    flag: 'AFN',
    decimalDigits: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'ALL',
    name: CurrencyDefaults.labels.currencyALL,
    symbol: 'Lek',
    flag: 'ALB',
    decimalDigits: 0,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: false,
    symbolOnLeft: false,
  ),
  (
    code: 'DZD',
    name: CurrencyDefaults.labels.currencyDZD,
    symbol: 'دج',
    flag: 'DZ',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: false,
    symbolOnLeft: false,
  ),
  (
    code: 'ARS',
    name: CurrencyDefaults.labels.currencyARS,
    symbol: '\$',
    flag: 'ARS',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'AMD',
    name: CurrencyDefaults.labels.currencyAMD,
    symbol: '֏',
    flag: 'AM',
    decimalDigits: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'AZN',
    name: CurrencyDefaults.labels.currencyAZN,
    symbol: '₼',
    flag: 'AZE',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'BHD',
    name: CurrencyDefaults.labels.currencyBHD,
    symbol: 'BD',
    flag: 'BHD',
    decimalDigits: 3,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'BDT',
    name: CurrencyDefaults.labels.currencyBDT,
    symbol: ' Tk',
    flag: 'BDT',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'BBD',
    name: CurrencyDefaults.labels.currencyBBD,
    symbol: '\$',
    flag: 'BBD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'BYN',
    name: CurrencyDefaults.labels.currencyBYN,
    symbol: 'Br',
    flag: 'BY',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'BZD',
    name: CurrencyDefaults.labels.currencyBZD,
    symbol: 'BZ\$',
    flag: 'BZD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'BMD',
    name: CurrencyDefaults.labels.currencyBMD,
    symbol: '\$',
    flag: 'BMD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'BTN',
    name: CurrencyDefaults.labels.currencyBTN,
    symbol: 'Nu.',
    flag: 'BTN',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'BOB',
    name: CurrencyDefaults.labels.currencyBOB,
    symbol: '\$b',
    flag: 'BOB',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'BAM',
    name: CurrencyDefaults.labels.currencyBAM,
    symbol: 'KM',
    flag: 'BA',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'BWP',
    name: CurrencyDefaults.labels.currencyBWP,
    symbol: 'P',
    flag: 'BW',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'BND',
    name: CurrencyDefaults.labels.currencyBND,
    symbol: '\$',
    flag: 'BND',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'BGN',
    name: CurrencyDefaults.labels.currencyBGN,
    symbol: 'лв',
    flag: 'BGN',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'BIF',
    name: CurrencyDefaults.labels.currencyBIF,
    symbol: 'FBu',
    flag: 'BI',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'KHR',
    name: CurrencyDefaults.labels.currencyKHR,
    symbol: '៛',
    flag: 'KHM',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: false,
  ),
  (
    code: 'KYD',
    name: CurrencyDefaults.labels.currencyKYD,
    symbol: '\$',
    flag: 'KYD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'XAF',
    name: CurrencyDefaults.labels.currencyXAF,
    symbol: 'FCFA',
    flag: null,
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'XOF',
    name: CurrencyDefaults.labels.currencyXOF,
    symbol: 'FCFA',
    flag: 'xof.png',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'CDF',
    name: CurrencyDefaults.labels.currencyCDF,
    symbol: 'FC',
    flag: 'CD',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'CRC',
    name: CurrencyDefaults.labels.currencyCRC,
    symbol: '₡',
    flag: 'CRC',
    decimalDigits: 0,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'DOP',
    name: CurrencyDefaults.labels.currencyDOP,
    symbol: 'RD\$',
    flag: 'DOP',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'EGP',
    name: CurrencyDefaults.labels.currencyEGP,
    symbol: '£',
    flag: 'EGP',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'ETB',
    name: CurrencyDefaults.labels.currencyETB,
    symbol: 'Br',
    flag: 'ETB',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'GMD',
    name: CurrencyDefaults.labels.currencyGMD,
    symbol: 'D',
    flag: 'GMD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: false,
  ),
  (
    code: 'GEL',
    name: CurrencyDefaults.labels.currencyGEL,
    symbol: '₾',
    flag: 'GEL',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'GHS',
    name: CurrencyDefaults.labels.currencyGHS,
    symbol: '₵',
    flag: 'GHS',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'GTQ',
    name: CurrencyDefaults.labels.currencyGTQ,
    symbol: 'Q',
    flag: 'GT',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'GYD',
    name: CurrencyDefaults.labels.currencyGYD,
    symbol: '\$',
    flag: 'GYD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'HTG',
    name: CurrencyDefaults.labels.currencyHTG,
    symbol: 'G',
    flag: 'HTI',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'ISK',
    name: CurrencyDefaults.labels.currencyISK,
    symbol: 'kr',
    flag: 'ISK',
    decimalDigits: 0,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'JMD',
    name: CurrencyDefaults.labels.currencyJMD,
    symbol: 'J\$',
    flag: 'JMD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'JOD',
    name: CurrencyDefaults.labels.currencyJOD,
    symbol: 'د.أ',
    flag: 'JO',
    decimalDigits: 3,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: false,
  ),
  (
    code: 'KZT',
    name: CurrencyDefaults.labels.currencyKZT,
    symbol: '〒',
    flag: 'KZT',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: '-',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'KES',
    name: CurrencyDefaults.labels.currencyKES,
    symbol: 'KSh',
    flag: 'KES',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'KWD',
    name: CurrencyDefaults.labels.currencyKWD,
    symbol: 'د.ك',
    flag: 'KWD',
    decimalDigits: 3,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'KGS',
    name: CurrencyDefaults.labels.currencyKGS,
    symbol: 'с',
    flag: 'KG',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'LAK',
    name: CurrencyDefaults.labels.currencyLAK,
    symbol: '₭',
    flag: 'LAK',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: false,
  ),
  (
    code: 'LRD',
    name: CurrencyDefaults.labels.currencyLRD,
    symbol: '\$',
    flag: 'LRD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'MKD',
    name: CurrencyDefaults.labels.currencyMKD,
    symbol: 'ден',
    flag: 'MKD',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'MWK',
    name: CurrencyDefaults.labels.currencyMWK,
    symbol: 'MK',
    flag: 'MWK',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'MUR',
    name: CurrencyDefaults.labels.currencyMUR,
    symbol: '₨',
    flag: 'MUR',
    decimalDigits: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'MDL',
    name: CurrencyDefaults.labels.currencyMDL,
    symbol: 'L',
    flag: 'MDL',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'MNT',
    name: CurrencyDefaults.labels.currencyMNT,
    symbol: '₮',
    flag: 'MNT',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'MAD',
    name: CurrencyDefaults.labels.currencyMAD,
    symbol: 'MAD',
    flag: 'MAD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'MZN',
    name: CurrencyDefaults.labels.currencyMZN,
    symbol: 'MT',
    flag: 'MZN',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'MMK',
    name: CurrencyDefaults.labels.currencyMMK,
    symbol: 'Ks',
    flag: 'MM',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'NAD',
    name: CurrencyDefaults.labels.currencyNAD,
    symbol: '\$',
    flag: 'NAD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'NPR',
    name: CurrencyDefaults.labels.currencyNPR,
    symbol: '₨',
    flag: 'NPR',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'NIO',
    name: CurrencyDefaults.labels.currencyNIO,
    symbol: 'C\$',
    flag: 'NIO',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'NGN',
    name: CurrencyDefaults.labels.currencyNGN,
    symbol: '₦',
    flag: 'NGN',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'OMR',
    name: CurrencyDefaults.labels.currencyOMR,
    symbol: '﷼',
    flag: 'OMR',
    decimalDigits: 3,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'PKR',
    name: CurrencyDefaults.labels.currencyPKR,
    symbol: '₨',
    flag: 'PKR',
    decimalDigits: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'PGK',
    name: CurrencyDefaults.labels.currencyPGK,
    symbol: 'K',
    flag: 'PGK',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'PYG',
    name: CurrencyDefaults.labels.currencyPYG,
    symbol: '₲',
    flag: 'PYG',
    decimalDigits: 0,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'PEN',
    name: CurrencyDefaults.labels.currencyPEN,
    symbol: 'S/.',
    flag: 'PEN',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'QAR',
    name: CurrencyDefaults.labels.currencyQAR,
    symbol: '﷼',
    flag: 'QAR',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'RWF',
    name: CurrencyDefaults.labels.currencyRWF,
    symbol: 'FRw',
    flag: 'RWA',
    decimalDigits: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'RSD',
    name: CurrencyDefaults.labels.currencyRSD,
    symbol: 'Дин.',
    flag: 'RSD',
    decimalDigits: 0,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'SCR',
    name: CurrencyDefaults.labels.currencySCR,
    symbol: '₨',
    flag: 'SC',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'SOS',
    name: CurrencyDefaults.labels.currencySOS,
    symbol: 'S',
    flag: 'SOS',
    decimalDigits: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'LKR',
    name: CurrencyDefaults.labels.currencyLKR,
    symbol: '₨',
    flag: 'LKR',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'SRD',
    name: CurrencyDefaults.labels.currencySRD,
    symbol: '\$',
    flag: 'SRD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'SYP',
    name: CurrencyDefaults.labels.currencySYP,
    symbol: 'LS',
    flag: 'SYP',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: false,
  ),
  (
    code: 'TZS',
    name: CurrencyDefaults.labels.currencyTZS,
    symbol: 'TSh',
    flag: 'TZS',
    decimalDigits: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'TTD',
    name: CurrencyDefaults.labels.currencyTTD,
    symbol: 'TT\$',
    flag: 'TTD',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'TND',
    name: CurrencyDefaults.labels.currencyTND,
    symbol: 'د.ت',
    flag: 'TN',
    decimalDigits: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: false,
  ),
  (
    code: 'UGX',
    name: CurrencyDefaults.labels.currencyUGX,
    symbol: 'USh',
    flag: 'UGX',
    decimalDigits: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: false,
    symbolOnLeft: true,
  ),
  (
    code: 'UAH',
    name: CurrencyDefaults.labels.currencyUAH,
    symbol: '₴',
    flag: 'UAH',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    hasSpace: false,
    symbolOnLeft: false,
  ),
  (
    code: 'UYU',
    name: CurrencyDefaults.labels.currencyUYU,
    symbol: '\$U',
    flag: 'UYU',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'VEF',
    name: CurrencyDefaults.labels.currencyVEF,
    symbol: 'Bs',
    flag: 'VEF',
    decimalDigits: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'VND',
    name: CurrencyDefaults.labels.currencyVND,
    symbol: '₫',
    flag: 'VND',
    decimalDigits: 0,
    thousandsSeparator: '.',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: false,
  ),
  (
    code: 'YER',
    name: CurrencyDefaults.labels.currencyYER,
    symbol: '﷼',
    flag: 'YER',
    decimalDigits: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
    hasSpace: true,
    symbolOnLeft: true,
  ),
  (
    code: 'ZMW',
    name: CurrencyDefaults.labels.currencyZMW,
    symbol: 'ZK',
    flag: 'ZM',
    decimalDigits: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    hasSpace: false,
    symbolOnLeft: true,
  ),
];
